### ISSUE TITLE
Stash un-staged files before test run and remove post-rewrite git hook

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/nearby-services-api#5] opened 2016-11-23 12:37 UTC
See [here](https://github.com/nhsuk/moment-opening-times/pull/41) for rational and changes required.

**Comment by st3v3nhunt** [comment] 2016-12-07 15:48
I've tried to implement this and it causes problems when attempting to amend the last commit message via `git commit --amend`. Until that is sorted the issue isn't going to be worked on again.

**Comment by st3v3nhunt** [comment] 2017-03-16 18:23
Closing due to it not working and an alternative approach to git hooks being needed with container based development environments

**Closed by st3v3nhunt** 2017-03-16 18:23 UTC
Labels: wontfix
